import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Demo with Giojs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to integrate with Giojs</h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/xxx.tsx</code>
        </p>
        <Link href="/createMsgSend">Go to CreateMsgSend demo page.</Link>
        <br />
        <br />
        <Link href="/wallet-keplr">Connect with wallet-keplr.</Link>
        <br />
        <br />
        <Link href="/wallet-gotabit-pc">
          Connect with wallet-gotabit on PC.
        </Link>
        <br />
        <br />
        <Link href="/wallet-gotabit-mobile">
          Connect with wallet-gotabit on Mobile.
        </Link>
        <br />
        <br />
        <Link href="/walletconnect">Connect with walletconnect.</Link>
        <br />
        <br />
        <Link href="/react-example">Connect with react.</Link>
        <br />
        <br />
        <Link href="/auth-wallet">Sign in with wallet.</Link>
      </main>
    </div>
  )
}

export default Home
